### ISSUE TITLE
run time problem

### ISSUE THREAD

**Issue by Patelrahul4884** [Insoler/Facial-Recognition-Based-Attendance-System#1]
after clicking authenticate yourself the program is quit.. any solution?

**Comment by Insoler** [comment]
> after clicking authenticate yourself the program is quit.. any solution?

Its a tkinter problem. The thing is, while authenticate is running, it needs to be linked to the other screen.py modules. But in doing so, it preloads all the libraries such as tensorflow in Add_new.py and recog.py. And hence would take much time to get loaded.
One of the solution could be to create a proper web dashboard instead of rudimentary tkinter one we made.

**Comment by Patelrahul4884** [comment]
can I get the perfect running code?

**Comment by Insoler** [comment]
Sure. If you really wanna try it:
In main.py,
**Write a function:**
`def next():`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `os.system('python Auth.py')`

And in main.py:
Replace line 86:
`c=Button(Home1, text="Authenticate yourself", command=quit,bd=20, bg="black", fg="red", 
                    font=('times new roman', 20),relief=RIDGE).pack()`
with
`c=Button(Home1, text="Authenticate yourself", command=next, bd=20, bg="black", fg="red", 
                    font=('times new roman', 20),relief=RIDGE).pack()`

You can do it this way, though its is not recommended as doing so may slow down the process as the modules are being imported for Auth.py in the meantime.

**Comment by Patelrahul4884** [comment]
### getting an error while running screen.py 
![image](https://user-images.githubusercontent.com/26384517/78526275-220b1300-77f7-11ea-8a2a-c24dd6e439de.png)

**Comment by Insoler** [comment]
Is this happening when running the whole screen.py or just singular modules? Since the problem is showing in Add_New.py, try running Add_New.py standalone once

**Comment by Patelrahul4884** [comment]
happening when running screen.py and I tried with Add.py but getting the same error
![image](https://user-images.githubusercontent.com/26384517/78527938-d27b1600-77fb-11ea-9744-f8ea3958cc71.png)

**Comment by Patelrahul4884** [comment]
downgrading numpy version worked Thanks Bro!

**Comment by Patelrahul4884** [comment]
now another issue after showing left right and center part of the face  camera is not closing and not saving data

**Comment by Insoler** [comment]
Try running 

> now another issue after showing left right and center part of the face camera is not closing and not saving data

Have you checked the facerec_128D.txt to see if its indeed not saving? 
Also after recording, press 'q' to save and exit.

**Comment by Patelrahul4884** [comment]
pressing q is also not working

**Comment by Insoler** [comment]
Nope. Just checked, its working.
![Screenshot from 2020-04-06 13-13-22](https://user-images.githubusercontent.com/48029688/78535103-36f0a200-7809-11ea-85e1-5f508011b270.png)

But still for you:
1> I have updated Add_New.py, please download that and check once more.
2> Check the versions of all dependencies from testing.txt

**Comment by Patelrahul4884** [comment]
the version that you define for TensorFlow is not exist

**Comment by Insoler** [comment]
The tensorflow 1.15.0 version does exist. 
![Annotation 2020-04-06 154155](https://user-images.githubusercontent.com/48029688/78547825-5396d500-781d-11ea-8884-2f99d656ac3e.png)

Whats your tensorflow version?

Try downloading Add_New.py again.

**Comment by Patelrahul4884** [comment]
not working for windows too
![image](https://user-images.githubusercontent.com/26384517/78637448-fefc6400-78c7-11ea-934f-a06e73e5127c.png)
having same issue not saving the data even after pressing 'q'

**Comment by Insoler** [comment]
1. Did you download the new Add_new.py?
2. Check all the dependencies testing.txt version.
